# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
  PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias dl='du -h --max-depth=1'
alias rm='rm -i'
alias ck='cmake .'
alias ..='cd ..'

  # WSL
alias open='explorer.exe'

  # X Display
export DISPLAY=:0
  # WSL 2
    # X Display, should get the host ip by '/etc/resolv.conf'
#host=$(cat /etc/resolv.conf | sed -n 's/^nameserver\W\(.*\)$/\1/p' | head -n 1)
#export DISPLAY=${host}:0

# CLion Configuration
ps -A | grep sshd &> /dev/null
if [[ $? -ne 0 ]]; then
  echo "Starting sshd and x410..."
  # Generated by 'fedora_setup_env.sh'
  sudo /usr/sbin/sshd
  sudo /usr/bin/ln -s /dev/null /dev/raw1394
  cmd.exe /c "start /b x410.exe"
  echo "Done!"
fi

# Enter home if start by windows terminal
if [ "$(pwd)" == "/mnt/c/Users/Honbey" ]; then
  cd ~
fi
